name: Deploy to server #directiva

on: push 

jobs:
    first_jobs:
        runs-on: ubuntu-latest

        steps:
            - name: Hola Mundo
              run: echo "Hola Mundo"
    second_jobs:
        needs: first_jobs    #nombre del job para crear una referencia, indicando que el segundo job necesita al primer job
        runs-on: ubuntu-latest

        steps:
            - name: Hola Mundo
              run: echo "Hola Mundo Segundo"